stages:
    - test-python
    - build-docs

before_script:
  - bash
  - eval `ssh-agent -s`
  - mkdir -p ~/.ssh
  - ssh-add <(echo "$SERIALBOX_SSH_KEY") 2>/dev/null
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

python3_5_unit_test:
  image: seriallab/python3.5dev
  stage: test-python
  script:
  - apt-get install -y git
  - export PYTHONPATH=$PYTHONPATH:$CI_PROJECT_DIR
  - git clone git@gitlab.com:serial-lab/EPCPyYes.git ../EPCPyYes
  - pip install -e ../EPCPyYes
  - pip install coverage
  - coverage run -m unittest discover
  - coverage report -m
  - coverage html
  artifacts:
    paths:
      - tests/htmlcov/

python3_6_unit_test:
  image: seriallab/python3.6dev
  stage: test-python
  script:
  - apt-get install -y git
  - export PYTHONPATH=$PYTHONPATH:$CI_PROJECT_DIR
  - git clone git@gitlab.com:serial-lab/EPCPyYes.git ../EPCPyYes
  - pip install -e ../EPCPyYes
  - pip install coverage
  - coverage run -m unittest discover
  - coverage report -m
  - coverage html
  artifacts:
    paths:
      - tests/htmlcov/

pages:
    image: seriallab/python3.5dev
    stage: build-docs
    script:
    - export PYTHONPATH=$PYTHONPATH:$CI_PROJECT_DIR
    - pip install sphinx sphinx_rtd_theme pygments ipython
    - make docs
    - mv docs/_build/html/ public/
    artifacts:
        paths:
        - public
    only:
      - master


